//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.1.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.andriipanasiuk.imagedownloader.service;

import android.content.Context;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class DownloadService_
    extends DownloadService
{


    public static DownloadService_.IntentBuilder_ intent(Context context) {
        return new DownloadService_.IntentBuilder_(context);
    }

    @Override
    public void waitForTasks() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    DownloadService_.super.waitForTasks();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<DownloadService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, DownloadService_.class);
        }

    }

}
